<?php
    include('functions.php');
    $_SESSION["loggedIn"]="";
    $_SESSION["fname"]="";
    $_SESSION['lname']="";
    $_SESSION["admin"]="";
    $_SESSION["loginEmail"]="";
    $_SESSION["hashedPassword"]="";
    session_abort();
    redirect("https://php-back2books.azurewebsites.net/");
?>